import {test} from 'node:test';import assert from 'node:assert/strict';import {Game} from '../src/game.js';
test('start choices and break pause do not allow extra hits',()=>{const g=new Game();assert.equal(g.hit(0),null);g.choose(false);for(let i=0;i<12;i++)g.hit(i*1200);assert.equal(g.mode,'break');assert.equal(g.hit(13000),null);g.choose(false);assert.equal(g.cups,0);assert.equal(g.mode,'play')});
test('ten cups end with caffeine overload without any further hits',()=>{const g=new Game();g.choose(true);let time=0;while(g.cups<10){const interval=g.breakEvery;for(let i=0;i<interval;i++)g.hit(time+=1200);assert.equal(g.mode,'break');g.choose(true)}assert.equal(g.outcome,'caffeine');assert.equal(g.mode,'ending');assert.equal(g.hit(time+=1200),null);assert.equal(g.choose(true),false);g.completeEnding();assert.equal(g.mode,'over');g.reset();assert.equal(g.cups,0);assert.equal(g.score,0);assert.equal(g.outcome,null)});
test('five fast hits trigger spin, spaced hits do not',()=>{const g=new Game();g.choose(false);for(let i=0;i<4;i++)g.hit(i*100);assert.equal(g.hit(400),'spin');assert.equal(g.hit(2500),'hit')});
test('sweet spot stays green and coffee cannot be added outside a break',()=>{const g=new Game();g.cups=6;assert.equal(g.stage.label,'THE SWEET SPOT');g.choose(false);assert.equal(g.choose(true),false);assert.equal(g.cups,6)});
import {stepBall} from '../src/physics.js';
test('four to six cups stay energetic and reach all screen edges',()=>{for(const cups of [4,5,6]){let b={x:400,y:250,vx:800,vy:620,radius:50,w:1000,h:600};const edges=new Set();for(let i=0;i<600;i++){b=stepBall(b,1/60,cups);if(b.x===50)edges.add('left');if(b.x===950)edges.add('right');if(b.y===50)edges.add('top');if(b.y===550)edges.add('bottom')}assert.equal(edges.size,4);assert.ok(Math.hypot(b.vx,b.vy)>900)}});
test('late fast balls remain inside the court on every bounce',()=>{let b={x:400,y:250,vx:1500,vy:-1700,radius:55,w:1000,h:600};for(let i=0;i<1000;i++){b=stepBall(b,1/60,10);assert.ok(b.x>=55&&b.x<=945);assert.ok(b.y>=55&&b.y<=545)}});
import {launchBall,chaosVelocity} from '../src/physics.js';
test('each edge scores once per collision; pauses ignore scoring and reset clears it',()=>{const g=new Game();g.choose(false);g.scoreEdges(['right','right']);assert.equal(g.scoreEdges(['left']),-15);assert.equal(g.scoreEdges(['top']),5);assert.equal(g.scoreEdges(['bottom']),-5);assert.equal(g.score,15);assert.equal(g.bestScore,30);g.mode='break';g.scoreEdges(['right']);assert.equal(g.score,15);g.reset();assert.equal(g.bestScore,0);const b={x:940,y:300,vx:800,vy:0,radius:50,w:1000,h:600};const bounce=stepBall(b,1/60,5);assert.deepEqual(bounce.edges,['right']);assert.deepEqual(stepBall(bounce,1/60,5).edges,[])});
test('sweet spot aims accurately; sleepy shots vary and pink shots lose control',()=>{const mid=launchBall('right',5,()=>.9);assert.ok(mid.vx>840);assert.ok(Math.abs(mid.vy)<30);const early=launchBall('right',1,()=>.9);assert.ok(Math.abs(early.vy/early.vx)>Math.abs(mid.vy/mid.vx));const pink=launchBall('right',10,()=>.1);assert.ok(pink.vx<0)});
test('pink trajectory trends toward negative edges over sustained bouncing',()=>{let state=7;const rand=()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296};let b={x:500,y:300,vx:1300,vy:200,radius:50,w:1000,h:600},score=0,left=0,right=0;for(let i=0;i<1800;i++){if(i%10===0)Object.assign(b,chaosVelocity(b.vx,b.vy,10,rand));b=stepBall(b,1/60,10);for(const e of b.edges){score+=({right:15,left:-15,top:5,bottom:-5})[e];if(e==='left')left++;if(e==='right')right++}}assert.ok(left>right);assert.ok(score<0)});

test('opening zero is safe but a played penalty falling to zero means LOVE',()=>{const g=new Game();g.choose(false);assert.equal(g.mode,'play');assert.equal(g.outcome,null);g.hit(1000);g.scoreEdges(['right']);g.scoreEdges(['left']);assert.equal(g.score,0);assert.equal(g.mode,'ending');assert.equal(g.outcome,'love');g.scoreEdges(['right']);assert.equal(g.score,0);assert.equal(g.hit(2000),null);g.completeEnding();assert.equal(g.mode,'over')});
test('penalties clamp at zero and only actual shots can trigger LOVE',()=>{const g=new Game();g.choose(false);g.scoreEdges(['left']);assert.equal(g.score,0);assert.equal(g.outcome,null);g.hit(1000);g.scoreEdges(['bottom']);assert.equal(g.outcome,'love');assert.equal(g.score,0)});
test('1000 points ends in a perfect warm-up and cannot score further',()=>{const g=new Game();g.choose(false);g.hit(1000);for(let i=0;i<67;i++)g.scoreEdges(['right']);assert.equal(g.score,1000);assert.equal(g.bestScore,1000);assert.equal(g.outcome,'perfect');assert.equal(g.mode,'over');g.scoreEdges(['left']);assert.equal(g.score,1000);assert.equal(g.hit(2000),null)});

test('later coffee choices arrive sooner and NO restarts the same interval',()=>{for(const [cups,interval] of [[0,12],[5,12],[6,6],[7,6],[8,3],[9,3]]){const g=new Game();g.cups=cups;g.choose(false);assert.equal(g.breakEvery,interval);for(let i=0;i<interval-1;i++){g.hit(i*1200);assert.equal(g.mode,'play')}assert.equal(g.hit(interval*1200),'break');g.choose(false);assert.equal(g.cups,cups);assert.equal(g.sinceBreak,0);assert.equal(g.breakEvery,interval)}});
