import {test,expect} from '@playwright/test';
// Seed reachable stage preconditions; real controls and collisions trigger the endings.
async function seed(page,values){await page.evaluate(async values=>Object.assign((await import('/src/main.js')).game,values),values)}
test('start sequence stays clear and first zero score does not end training',async({page})=>{await page.goto('/');await expect(page.locator('#start-button')).toBeVisible();await expect(page.locator('#coffee-choice')).toBeHidden();await page.locator('#start-button').click();await expect(page.locator('#dialog-title')).toHaveText('Start with a coffee?');await expect(page.locator('.intro')).toBeHidden();await expect(page.locator('.coffee-rail')).toHaveCSS('opacity','0');await page.locator('#coffee-choice').click();await expect(page.locator('#score')).toHaveText('0');await expect(page.locator('#love')).toBeHidden();await expect(page.locator('#hit')).toBeVisible()});
test('zero from a real penalty animates LOVE twice then shows coffee lover ending',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#no-choice').click();await seed(page,{cups:6,score:5});await page.locator('[data-direction="down"]').click();await page.locator('#hit').click();await expect(page.locator('#love')).toBeVisible();await expect(page.locator('#love')).toHaveCSS('animation-iteration-count','2');await expect(page.locator('#score')).toHaveText('0');await expect(page.locator('#hit')).toBeHidden();await expect(page.locator('#dialog-title')).toHaveText('LOVE — 0 points.');await expect(page.locator('#end-copy')).toContainText('Coffee lover.');await page.locator('#restart').click();await expect(page.locator('#start-button')).toBeVisible();await expect(page.locator('#love')).toBeHidden()});
test('tenth coffee locks play, gets dizzy, and ends on black',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#coffee-choice').click();await seed(page,{cups:9,score:500,sinceBreak:11});await page.locator('#hit').click();await expect(page.locator('#dialog-title')).toHaveText('Coffee Break?');await page.locator('#coffee-choice').click();await expect(page.locator('body')).toHaveAttribute('data-mode','ending');await expect(page.locator('main')).toHaveCSS('animation-name','caffeine-dizzy');await expect(page.locator('#hit')).toBeHidden();await expect(page.locator('#cups-count')).toHaveText('10');await expect(page.locator('#love')).toBeHidden();await expect(page.locator('#dialog-title')).toHaveText('Too much caffeine.');await expect(page.locator('#dialog-title')).toBeVisible();await expect(page.locator('.game-over .overlay')).toHaveCSS('background-color','rgb(0, 0, 0)');await page.locator('#restart').click();await expect(page.locator('#start-button')).toBeVisible()});
test('real right-edge collision crosses 1000 and ends in perfect warm-up',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#no-choice').click();await seed(page,{cups:6,score:990,bestScore:990});await page.locator('#hit').click();await expect(page.locator('#dialog-title')).toHaveText('Perfect warm-up.');await expect(page.locator('#dialog-title')).toBeVisible();await expect(page.locator('#score')).toHaveText('1000');await expect(page.locator('#end-score')).toContainText('Final score: 1000');await expect(page.locator('#hit')).toBeHidden();const end=await page.locator('#court').boundingBox();const viewport=page.viewportSize();expect(end.width).toBe(viewport.width);expect(end.height).toBe(viewport.height)});
test('no coffee, physics bounds, keyboard and instructions',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#no-choice').click();await page.locator('#hit').click();const a=await page.locator('#ball').boundingBox();await page.waitForTimeout(300);const b=await page.locator('#ball').boundingBox();expect(Math.abs(a.x-b.x)+Math.abs(a.y-b.y)).toBeGreaterThan(5);const c=await page.locator('#court').boundingBox();expect(b.x).toBeGreaterThanOrEqual(c.x);expect(b.x+b.width).toBeLessThanOrEqual(c.x+c.width);await page.locator('#rules-button').click();await expect(page.locator('#rules')).toBeVisible();await page.locator('#close-rules').click();await page.locator('body').click({position:{x:5,y:5}});await page.keyboard.press('Space');await expect(page.locator('#hit-count')).toHaveText('02');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()});

test('complete Chalkduster font is loaded for all text and racket labels',async({page})=>{await page.goto('/');await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.fonts.check('16px Chalkduster','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'))).toBeTruthy();for(const id of ['start-button','dialog-title','hit','rules-button','cups-count','callout','end-copy'])expect(await page.locator('#'+id).evaluate(el=>getComputedStyle(el).fontFamily)).toContain('Chalkduster')});

test('feedback changes position and color, uses Chalkduster, and animates',async({page})=>{await page.goto('/');await expect(page.locator('.intro h1')).toHaveCount(0);await page.locator('#start-button').click();await page.locator('#coffee-choice').click();const snapshot=()=>page.locator('#callout').evaluate(el=>({left:el.style.left,top:el.style.top,color:el.style.color,font:getComputedStyle(el).fontFamily,animation:getComputedStyle(el).animationName}));const first=await snapshot();for(let i=0;i<3;i++)await page.locator('#hit').click();const next=await snapshot();expect([next.left,next.top]).not.toEqual([first.left,first.top]);expect(next.color).not.toBe(first.color);expect(next.font).toContain('Chalkduster');expect(next.animation).toBe('shot-pop')});

test('coffee choices do not praise shots and Break Point stays in the break dialog',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#coffee-choice').click();await expect(page.locator('#callout')).toHaveText('');await expect(page.locator('#break-label')).toBeHidden();for(let i=0;i<12;i++)await page.locator('#hit').click();await expect(page.locator('#break-label')).toBeVisible();await expect(page.locator('#callout')).not.toHaveClass(/pop/);await page.locator('#no-choice').click();await expect(page.locator('#break-label')).toBeHidden();await expect(page.locator('#callout')).toHaveText('');});
test('racket aim controls and keyboard change direction and right edge adds points',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#no-choice').click();await page.locator('[data-direction="up"]').click();await expect(page.locator('[data-direction="up"]')).toHaveAttribute('aria-pressed','true');await page.keyboard.press('ArrowRight');await expect(page.locator('[data-direction="right"]')).toHaveAttribute('aria-pressed','true');for(let i=0;i<4;i++){for(let j=0;j<12;j++)await page.locator('#hit').click();await page.locator('#coffee-choice').click()}await page.locator('[data-direction="right"]').click();await page.locator('#hit').click();await expect.poll(async()=>Number(await page.locator('#best-score').textContent())).toBeGreaterThan(0);await expect(page.locator('#score')).not.toHaveText('0');});

test('landscape court fits wide and short laptop windows without clipped controls',async({page})=>{for(const viewport of [{width:1440,height:760},{width:1920,height:900},{width:1280,height:650},{width:1024,height:600}]){await page.setViewportSize(viewport);await page.goto('/');await page.evaluate(()=>document.fonts.ready);await page.locator('#start-button').click();await page.locator('#no-choice').click();await page.waitForTimeout(150);const frame=await page.locator('.game-shell').boundingBox();expect(frame.width/frame.height).toBeCloseTo(1366/768,2);expect(frame.y).toBeGreaterThanOrEqual(0);expect(frame.y+frame.height).toBeLessThanOrEqual(viewport.height);for(const selector of ['#hit','#direction-pad','.controls','.cup-slot:last-child']){const box=await page.locator(selector).boundingBox();expect(box.y+box.height).toBeLessThanOrEqual(viewport.height);expect(box.x+box.width).toBeLessThanOrEqual(viewport.width)}expect(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1)).toBeTruthy()}});

test('NO at Coffee Break preserves the paused ball position',async({page})=>{await page.goto('/');await page.locator('#start-button').click();await page.locator('#coffee-choice').click();for(let i=0;i<12;i++)await page.locator('#hit').click();await expect(page.locator('#dialog-title')).toHaveText('Coffee Break?');await page.waitForTimeout(100);const paused=await page.locator('#ball').boundingBox();await page.locator('#no-choice').click();await page.waitForTimeout(100);const resumed=await page.locator('#ball').boundingBox();expect(resumed.x+resumed.width/2).toBeCloseTo(paused.x+paused.width/2,1);expect(resumed.y+resumed.height/2).toBeCloseTo(paused.y+paused.height/2,1);await expect(page.locator('#cups-count')).toHaveText('1')});
